# Generated by Django 3.1.7 on 2021-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaken',
            name='submittedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.CharField(blank=True, max_length=2555),
        ),
    ]
