# Generated by Django 3.1.7 on 2021-04-10 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0002_auto_20210408_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='assigned_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='due_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='testTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.test')),
            ],
            options={
                'unique_together': {('test', 'student')},
            },
        ),
    ]
