# Generated by Django 3.1.7 on 2021-04-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_auto_20210410_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='assigned_time',
            new_name='posting_time',
        ),
    ]
