# Generated by Django 3.1.7 on 2021-04-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0004_auto_20210411_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='posting_time',
            new_name='assign_time',
        ),
    ]
