# Generated by Django 3.1.7 on 2021-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0005_auto_20210411_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='assign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
