# Generated by Django 3.1.7 on 2021-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0006_auto_20210411_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='assign_time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='due_time',
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
